Repository Mattherix/ViperDefender, pull requests merged in 2023-07, with the labels that each got.

#3 Add files via upload
  Historique des ransomwares.pdf
  Les différents ransomware.docx
  Misini_Leutrim_TDB.pdf
  documents.md
Labels: documentation

#22 Use case Diagram et UML
  Sequence Diagram.drawio
  Sequence Diagram.drawio.pdf
  Use Case Diagram v1.drawio
  Use Case Diagram v1.pdf
Labels: documentation

#21 feat(readme): V1
  README.md
Labels: documentation

#26 Feat/link to db
  src/client/app.py
  src/launch-vm/main.py
  src/launch-vm/requirements.txt
  src/orchestrator/FIles/__init__.py
  src/orchestrator/FIles/function.json
  src/orchestrator/FIles/sample.dat
  src/orchestrator/Session/__init__.py
  src/orchestrator/Session/db.py
  src/orchestrator/Session/function.json
  src/orchestrator/Session/sample.dat
  src/orchestrator/insomnia.config.json
  src/orchestrator/requirements.txt
Labels: enhancement

#25 Lancement de vm via python
  src/launch-vm/main.py
  src/launch-vm/requirements.txt
Labels: enhancement

#20 Verification script
  .github/workflows/build_verification.yml
  .gitignore
  .vscode/settings.json
  src/orchestrator/EventGridTrigger1/__init__.py
  src/orchestrator/EventGridTrigger1/function.json
  src/orchestrator/EventGridTrigger1/sample.dat
  src/verification/.gitignore
  src/verification/check_id.py
  src/verification/download.py
  src/verification/events.py
  src/verification/main.py
  src/verification/main.spec
  src/verification/requirements.txt
  src/verification/verification.py
Labels: enhancement

#29 feat(client): move to quarantine
  src/client/app.py
Labels: enhancement

#30 Fix/client requirements
  src/client/app.py
  src/client/requirements.txt
Labels: bug

#32 fix(client): case of crdownload files
  src/client/app.py
Labels: bug

#33 Add insomnia config in readme
  README.md
Labels: documentation

#31 Compiler application client
  .github/workflows/build_client.yml
  .github/workflows/build_verification.yml
  .vscode/settings.json
  src/client/app.py
  src/client/main.spec
  src/client/requirements.txt
Labels: enhancement

#35 fix(client): remove delete_file
  src/client/app.py
  src/client/setup-on-launch.py
Labels: bug

#36 fix(client): big files virustotal
  src/orchestrator/TestFile/__init__.py
Labels: bug

#37 Ajouter un license a notre code
  LICENSE
Labels: enhancement
